#!/usr/bin/env python3
"""
Exports the chip data layer into two flavors of consolidated JSON:

  dist/chips.config.json
      Flat, minimal — value-only, no provenance clutter. Meant for direct
      consumption by build tooling / config generators (e.g. a PlatformIO
      board-capability check, a CLI board picker, a form autofill). If you
      just need "does ESP32-C6 have Ethernet: yes/no", this is the file.

  dist/chips.ai_context.json
      Verbose, provenance-preserving — every field keeps its source_ref
      resolved to a full citation (title, version, url, accessed date) and
      its last_verified date. Meant to be loaded into an AI coding
      assistant's context at generation time — e.g. "write ESP-IDF init
      code for whichever chip in this repo has an integrated Ethernet MAC
      and cite where that capability claim comes from." An agent reading
      this file can answer without re-fetching a datasheet AND can show
      its receipts.

Both are build artifacts of the data layer, never edited by hand — same
principle as the README table generator.

Usage:
    python3 tools/export_config.py
"""

import glob
import json
import yaml
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def load_yaml(path):
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_sources():
    registry = {}
    for path in sorted(glob.glob(str(ROOT / "data" / "sources" / "*.yaml"))):
        for src in load_yaml(Path(path)).get("sources", []):
            registry[src["id"]] = src
    return registry


def strip_provenance(obj):
    """Recursively reduce {value, source_ref, last_verified, ...} leaves
    down to just their value, for the lightweight config export."""
    if isinstance(obj, dict):
        if "value" in obj and "source_ref" in obj:
            return obj["value"]
        return {k: strip_provenance(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [strip_provenance(v) for v in obj]
    return obj


def resolve_provenance(obj, sources):
    """Recursively expand source_ref -> full citation, for the AI-context
    export. Keeps value + last_verified + resolved citation together."""
    if isinstance(obj, dict):
        if "value" in obj and "source_ref" in obj:
            src = sources.get(obj["source_ref"], {})
            out = {
                "value": obj["value"],
                "last_verified": obj.get("last_verified"),
                "citation": {
                    "title": src.get("title"),
                    "version": src.get("version"),
                    "url": src.get("url"),
                    "status": src.get("status"),
                },
            }
            if "detail" in obj:
                out["detail"] = obj["detail"]
            if "note" in obj:
                out["note"] = obj["note"]
            return out
        return {k: resolve_provenance(v, sources) for k, v in obj.items()}
    if isinstance(obj, list):
        return [resolve_provenance(v, sources) for v in obj]
    return obj


def main():
    sources = load_sources()
    chip_files = sorted(glob.glob(str(ROOT / "data" / "chips" / "*.yaml")))
    chips = [load_yaml(Path(p)) for p in chip_files]

    dist = ROOT / "dist"
    dist.mkdir(exist_ok=True)

    # --- lightweight config export ---
    config_out = {c["id"]: strip_provenance(c) for c in chips}
    config_path = dist / "chips.config.json"
    with open(config_path, "w", encoding="utf-8") as f:
        json.dump(config_out, f, indent=2, ensure_ascii=False)
    print(f"wrote {config_path.relative_to(ROOT)}  ({len(config_out)} chips, value-only)")

    # --- AI-context export, provenance-preserving ---
    ai_out = {
        "$schema_note": (
            "Provenance-preserving chip capability data for ESP32Features. "
            "Every field cites its source; treat status=no_public_pdf fields "
            "as lower-confidence than a verified datasheet citation. "
            "Generated by tools/export_config.py — do not hand-edit."
        ),
        "chips": {c["id"]: resolve_provenance(c, sources) for c in chips},
    }
    ai_path = dist / "chips.ai_context.json"
    with open(ai_path, "w", encoding="utf-8") as f:
        json.dump(ai_out, f, indent=2, ensure_ascii=False)
    print(f"wrote {ai_path.relative_to(ROOT)}  ({len(chips)} chips, full provenance)")


if __name__ == "__main__":
    main()
